---
version: '3'
services:
  go-elasticsearch-alerts:
    build: .
    container_name: go-elasticsearch-alerts
    environment:
      - GO_ELASTICSEARCH_ALERTS_CONFIG_FILE=/build/config/config.json
      - GO_ELASTICSEARCH_ALERTS_RULES_DIR=/build/config/rules
    volumes:
      - gea_data:/usr/share/go-elasticsearch-alerts/data
    networks:
      - geanet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_main_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - geanet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_main_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - geanet

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_main_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - geanet

  consul-gea:
    image: consul
    container_name: consul-gea
    volumes:
      - consul_gea_data:/usr/share/consul/data
    ports:
      - 8500:8500
    networks:
      - geanet

volumes:
  gea_data:
    driver: local
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  consul_gea_data:
    driver: local

networks:
  geanet:
    driver: bridge