---
# ====================================
#
#            RESOURCE TYPES
#
# ====================================
resource_types:
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource
    channel: '#build'

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr


# ====================================
#
#            RESOURCES
#
# ====================================
resources:
- name: test-pull-request
  type: pull-request
  source:
    private_key: ((github-private-key))
    access_token: ((github-access-token))
    repo: morningconsult/docker-credential-vault-login
    uri: ((github-repo))
    base: master

- name: new-release
  type: git
  source:
    private_key: ((github-private-key))
    access_token: ((github-access-token))
    uri: ((github-repo))
    branch: master
    tag_filter: 'v[0-9]*'

- name: golang
  type: docker-image
  source:
    repository: golang
    tag: 1.11.3-alpine3.8

- name: slack
  type: slack-alert
  source:
    url: ((slack-webhook))
    channel: '#build'

# ====================================
#
#            JOBS
#
# ====================================
jobs:
- name: test-pr
  build_logs_to_retain: 30
  serial: true
  plan:
  - get: test-pull-request
    trigger: true
  - put: test-pull-request
    params:
      repository: test-pull-request
      status: running
  - get: golang
  - task: test-pr
    image: golang
    file: test-pull-request/ci/tasks/test-pull-request.yml
    on_success:
      put: test-pull-request
      params:
        repository: test-pull-request
        status: success
        context: $BUILD_JOB_NAME
        comment: test-pull-request/ci/pr_test_success
    on_failure:
      put: test-pull-request
      params:
        repository: test-pull-request
        status: failed
        context: $BUILD_JOB_NAME
        comment: test-pull-request/ci/pr_test_failure

- name: build-release
  serial: true
  plan:
  - aggregate:
    - get: new-release
      trigger: true
    - get: golang
  - task: test-and-build
    image: golang
    file: new-release/ci/tasks/build-release.yml
    params:
      GITHUB_TOKEN: ((github-access-token))
    on_failure:
      put: slack
      params: {alert_type: failed}
    on_abort:
      put: slack
      params: {alert_type: aborted}
