---
# ====================================
#
#            RESOURCE TYPES
#
# ====================================
resource_types:
- name: slack-alert
  type: registry-image
  source:
    repository: arbourd/concourse-slack-alert-resource

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource


# ====================================
#
#            RESOURCES
#
# ====================================
resources:
- name: test-pull-request
  type: pull-request
  source:
    repository: morningconsult/go-elasticsearch-alerts
    access_token: ((github-access-token))

- name: new-release
  type: git
  source:
    private_key: ((github-private-key))
    access_token: ((github-access-token))
    uri: ((github-repo))
    branch: master
    tag_filter: 'v*'

- name: golang
  type: registry-image
  source:
    repository: golang
    tag: 1.11.4-alpine3.8

- name: slack
  type: slack-alert
  source:
    url: ((slack-webhook))
    channel: '#build'

# ====================================
#
#            JOBS
#
# ====================================
jobs:
- name: test-pr
  build_logs_to_retain: 30
  serial: true
  plan:
  - aggregate:
    - get: test-pull-request
      trigger: true
    - get: golang
  - put: test-pull-request
    params:
      path: test-pull-request
      status: pending
  - task: test-pr
    image: golang
    file: test-pull-request/ci/tasks/test-pull-request.yml
    on_success:
      put: test-pull-request
      params:
        path: test-pull-request
        status: success
        context: test-pr
    on_failure:
      put: test-pull-request
      params:
        path: test-pull-request
        status: failure
        context: test-pr
    on_abort:
      put: test-pull-request
      params:
        path: test-pull-request
        status: error
        context: test-pr

- name: build-release
  serial: true
  plan:
  - aggregate:
    - get: new-release
      trigger: true
    - get: golang
  - task: test-and-build
    image: golang
    file: new-release/ci/tasks/build-release.yml
    params:
      GITHUB_TOKEN: ((github-access-token))
    on_failure:
      put: slack
      params: {alert_type: failed}
    on_abort:
      put: slack
      params: {alert_type: aborted}
