name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - VERSION
      - CHANGELOG.md
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run linting and tests
    runs-on: ubuntu-18.04
    container:
      image: golang:1.15.8-alpine3.13
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run linting
      env:
        CGO_ENABLED: '0'
      run: |
        apk add -qU --no-cache --no-progress curl git
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin "v1.36.0"
        golangci-lint run ./...

    - name: Run tests
      env:
        CGO_ENABLED: '0'
        GO111MODULE: 'on'
      run: go test ./...
